// Mock data for movies
export const mockMovies = [
  {
    id: 1,
    title: "Dune",
    originalTitle: "Dune",
    description:
      "Paul Atreides, un jeune homme brillant et doué, né pour connaître un destin plus grand que lui-même, doit se rendre sur la planète la plus dangereuse de l'univers pour assurer l'avenir de sa famille et de son peuple.",
    releaseDate: "2021-09-15",
    duration: "2h 35min",
    rating: 8.0,
    genres: ["Science-Fiction", "Aventure", "Drame"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/8g18jFHCLXk",
    videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
    featured: true,
    views: 125890,
    cast: [
      { name: "Timothée Chalamet", character: "Paul Atreides", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Rebecca Ferguson", character: "Lady Jessica", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Oscar Isaac", character: "Duke Leto Atreides", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Jason Momoa", character: "Duncan Idaho", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Zendaya", character: "Chani", photo: "/placeholder.svg?height=200&width=200" },
    ],
    director: "Denis Villeneuve",
    videoQuality: "4K",
    language: "Anglais",
    subtitles: ["Français", "Anglais", "Espagnol"],
    vipOnly: false,
  },
  {
    id: 2,
    title: "The Matrix Resurrections",
    originalTitle: "The Matrix Resurrections",
    description:
      "Neo vit une vie ordinaire à San Francisco, où son thérapeute lui prescrit des pilules bleues. Jusqu'au jour où Morpheus lui offre la pilule rouge et rouvre son esprit au monde de la Matrice.",
    releaseDate: "2021-12-22",
    duration: "2h 28min",
    rating: 5.7,
    genres: ["Science-Fiction", "Action", "Aventure"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/9ix7TUGVYIo",
    videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
    featured: false,
    views: 98450,
    cast: [
      { name: "Keanu Reeves", character: "Neo", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Carrie-Anne Moss", character: "Trinity", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Yahya Abdul-Mateen II", character: "Morpheus", photo: "/placeholder.svg?height=200&width=200" },
    ],
    director: "Lana Wachowski",
    videoQuality: "HD",
    language: "Anglais",
    subtitles: ["Français", "Anglais"],
    vipOnly: false,
  },
  {
    id: 3,
    title: "Interstellar",
    originalTitle: "Interstellar",
    description:
      "Un groupe d'explorateurs utilise un trou de ver récemment découvert pour surpasser les limites du voyage spatial humain et conquérir les vastes distances d'un voyage interstellaire.",
    releaseDate: "2014-11-05",
    duration: "2h 49min",
    rating: 8.6,
    genres: ["Science-Fiction", "Aventure", "Drame"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/zSWdZVtXT7E",
    videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
    featured: true,
    views: 245780,
    cast: [
      { name: "Matthew McConaughey", character: "Cooper", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Anne Hathaway", character: "Brand", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Jessica Chastain", character: "Murphy", photo: "/placeholder.svg?height=200&width=200" },
    ],
    director: "Christopher Nolan",
    videoQuality: "4K",
    language: "Anglais",
    subtitles: ["Français", "Anglais", "Espagnol", "Allemand"],
    vipOnly: false,
  },
  {
    id: 4,
    title: "Inception",
    originalTitle: "Inception",
    description:
      "Un voleur qui s'infiltre dans les rêves des autres pour y voler leurs secrets se voit offrir une chance de retrouver sa vie normale en réalisant l'implantation d'une idée dans l'esprit d'une personne.",
    releaseDate: "2010-07-16",
    duration: "2h 28min",
    rating: 8.8,
    genres: ["Science-Fiction", "Action", "Aventure"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/YoHD9XEInc0",
    videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
    featured: false,
    views: 312450,
    cast: [
      { name: "Leonardo DiCaprio", character: "Cobb", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Joseph Gordon-Levitt", character: "Arthur", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Ellen Page", character: "Ariadne", photo: "/placeholder.svg?height=200&width=200" },
    ],
    director: "Christopher Nolan",
    videoQuality: "HD",
    language: "Anglais",
    subtitles: ["Français", "Anglais"],
    vipOnly: false,
  },
  {
    id: 5,
    title: "The Dark Knight",
    originalTitle: "The Dark Knight",
    description:
      "Batman s'allie au procureur de Gotham, Harvey Dent, pour démanteler le crime organisé qui sévit dans la ville. Mais bientôt, ils se retrouvent face à un psychopathe connu sous le nom du Joker.",
    releaseDate: "2008-07-18",
    duration: "2h 32min",
    rating: 9.0,
    genres: ["Action", "Crime", "Drame"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/EXeTwQWrcwY",
    videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
    featured: false,
    views: 425670,
    cast: [
      { name: "Christian Bale", character: "Bruce Wayne / Batman", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Heath Ledger", character: "Joker", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Aaron Eckhart", character: "Harvey Dent", photo: "/placeholder.svg?height=200&width=200" },
    ],
    director: "Christopher Nolan",
    videoQuality: "HD",
    language: "Anglais",
    subtitles: ["Français", "Anglais", "Espagnol"],
    vipOnly: false,
  },
  {
    id: 6,
    title: "Parasite",
    originalTitle: "Gisaengchung",
    description:
      "Toute la famille de Ki-taek est au chômage, et s'intéresse fortement au train de vie de la richissime famille Park. Un jour, leur fils réussit à se faire recommander pour donner des cours particuliers d'anglais chez les Park.",
    releaseDate: "2019-05-30",
    duration: "2h 12min",
    rating: 8.5,
    genres: ["Drame", "Thriller", "Comédie"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/isOGD_7hNIY",
    videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
    featured: false,
    views: 187320,
    cast: [
      { name: "Song Kang-ho", character: "Ki-taek", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Lee Sun-kyun", character: "Dong-ik", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Cho Yeo-jeong", character: "Yeon-kyo", photo: "/placeholder.svg?height=200&width=200" },
    ],
    director: "Bong Joon-ho",
    videoQuality: "4K",
    language: "Coréen",
    subtitles: ["Français", "Anglais", "Espagnol"],
    vipOnly: false,
  },
  {
    id: 7,
    title: "Joker",
    originalTitle: "Joker",
    description:
      "Dans les années 1980, à Gotham City, Arthur Fleck, un comédien de stand-up raté, bascule dans la folie et devient le Joker.",
    releaseDate: "2019-10-04",
    duration: "2h 2min",
    rating: 8.4,
    genres: ["Crime", "Drame", "Thriller"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/zAGVQLHvwOY",
    videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
    featured: false,
    views: 276540,
    cast: [
      { name: "Joaquin Phoenix", character: "Arthur Fleck / Joker", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Robert De Niro", character: "Murray Franklin", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Zazie Beetz", character: "Sophie Dumond", photo: "/placeholder.svg?height=200&width=200" },
    ],
    director: "Todd Phillips",
    videoQuality: "4K",
    language: "Anglais",
    subtitles: ["Français", "Anglais"],
    vipOnly: false,
  },
  {
    id: 8,
    title: "Avengers: Endgame",
    originalTitle: "Avengers: Endgame",
    description:
      "Après les événements dévastateurs d'Avengers: Infinity War, l'univers est en ruines. Avec l'aide des alliés restants, les Avengers se rassemblent une fois de plus afin de tenter d'inverser les actions de Thanos et de restaurer l'équilibre dans l'univers.",
    releaseDate: "2019-04-26",
    duration: "3h 1min",
    rating: 8.4,
    genres: ["Action", "Aventure", "Science-Fiction"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/TcMBFSGVi1c",
    videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
    featured: false,
    views: 543210,
    cast: [
      { name: "Robert Downey Jr.", character: "Tony Stark / Iron Man", photo: "/placeholder.svg?height=200&width=200" },
      {
        name: "Chris Evans",
        character: "Steve Rogers / Captain America",
        photo: "/placeholder.svg?height=200&width=200",
      },
      { name: "Mark Ruffalo", character: "Bruce Banner / Hulk", photo: "/placeholder.svg?height=200&width=200" },
    ],
    director: "Anthony Russo, Joe Russo",
    videoQuality: "4K",
    language: "Anglais",
    subtitles: ["Français", "Anglais", "Espagnol", "Allemand"],
    vipOnly: false,
  },
  {
    id: 9,
    title: "Le Nouveau Film",
    originalTitle: "The New Movie",
    description: "Un film en cours de préparation qui promet d'être révolutionnaire.",
    releaseDate: "2023-12-25",
    duration: "2h 15min",
    rating: 0,
    genres: ["Action", "Aventure"],
    status: "draft",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "",
    videoFile: "",
    featured: false,
    views: 0,
    cast: [
      { name: "Acteur Principal", character: "Personnage Principal", photo: "/placeholder.svg?height=200&width=200" },
    ],
    director: "Réalisateur Talentueux",
    videoQuality: "4K",
    language: "Français",
    subtitles: ["Français", "Anglais"],
    vipOnly: false,
  },
  {
    id: 10,
    title: "Projet Secret",
    originalTitle: "Secret Project",
    description: "Un projet top secret dont les détails seront révélés prochainement.",
    releaseDate: "2024-05-15",
    duration: "2h 30min",
    rating: 0,
    genres: ["Thriller", "Mystère"],
    status: "draft",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "",
    videoFile: "",
    featured: false,
    views: 0,
    cast: [],
    director: "Réalisateur Mystère",
    videoQuality: "HD",
    language: "Anglais",
    subtitles: ["Français", "Anglais"],
    vipOnly: false,
  },
  // Contenu VIP exclusif
  {
    id: 11,
    title: "Exclusivité VIP: Cosmos",
    originalTitle: "VIP Exclusive: Cosmos",
    description:
      "Une odyssée visuelle à travers l'univers, avec des images spectaculaires capturées par les télescopes les plus avancés.",
    releaseDate: "2023-10-15",
    duration: "2h 45min",
    rating: 9.2,
    genres: ["Documentaire", "Science", "Espace"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/example1",
    videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
    featured: true,
    views: 45680,
    cast: [{ name: "Neil deGrasse Tyson", character: "Narrateur", photo: "/placeholder.svg?height=200&width=200" }],
    director: "Ann Druyan",
    videoQuality: "8K",
    language: "Français",
    subtitles: ["Français", "Anglais", "Espagnol", "Allemand", "Italien"],
    vipOnly: true,
  },
  {
    id: 12,
    title: "Exclusivité VIP: Avant-première Mondiale",
    originalTitle: "VIP Exclusive: World Premiere",
    description: "Soyez parmi les premiers à découvrir ce chef-d'œuvre cinématographique avant sa sortie officielle.",
    releaseDate: "2023-11-30",
    duration: "2h 20min",
    rating: 8.9,
    genres: ["Action", "Thriller", "Drame"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/example2",
    videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
    featured: true,
    views: 32450,
    cast: [
      { name: "Acteur Célèbre", character: "Personnage Principal", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Actrice Renommée", character: "Personnage Secondaire", photo: "/placeholder.svg?height=200&width=200" },
    ],
    director: "Réalisateur de Renom",
    videoQuality: "4K HDR",
    language: "Français",
    subtitles: ["Français", "Anglais"],
    vipOnly: true,
  },
]

// Mock data for series
export const mockSeries = [
  {
    id: 1,
    title: "Stranger Things",
    originalTitle: "Stranger Things",
    description:
      "Quand un jeune garçon disparaît, une petite ville découvre une affaire mystérieuse, des expériences secrètes, des forces surnaturelles terrifiantes... et une fillette.",
    releaseDate: "2016-07-15",
    duration: "50min par épisode",
    rating: 8.7,
    genres: ["Drame", "Fantastique", "Horreur"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/b9EkMc79ZSU",
    featured: true,
    views: 876540,
    cast: [
      { name: "Millie Bobby Brown", character: "Eleven", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Finn Wolfhard", character: "Mike Wheeler", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Winona Ryder", character: "Joyce Byers", photo: "/placeholder.svg?height=200&width=200" },
    ],
    creator: "The Duffer Brothers",
    language: "Anglais",
    subtitles: ["Français", "Anglais", "Espagnol"],
    vipOnly: false,
    seasons: [
      {
        number: 1,
        title: "Saison 1",
        releaseDate: "2016-07-15",
        episodes: [
          {
            number: 1,
            title: "La disparition de Will Byers",
            description:
              "Le soir du 6 novembre 1983, dans la petite ville de Hawkins dans l'Indiana, le jeune Will Byers, douze ans, disparaît brusquement sans laisser de traces.",
            duration: "47min",
            thumbnail: "/placeholder.svg?height=300&width=500",
            videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
          },
          {
            number: 2,
            title: "La barjot de Maple Street",
            description:
              "Mike, Lucas et Dustin tentent de parler avec la jeune fille qu'ils ont trouvée dans les bois.",
            duration: "55min",
            thumbnail: "/placeholder.svg?height=300&width=500",
            videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
          },
        ],
      },
      {
        number: 2,
        title: "Saison 2",
        releaseDate: "2017-10-27",
        episodes: [
          {
            number: 1,
            title: "MADMAX",
            description:
              "Alors que la ville se prépare pour Halloween, un rival met en doute le record de Dustin au jeu d'arcade, et des visions éveillées tourmentent Will.",
            duration: "48min",
            thumbnail: "/placeholder.svg?height=300&width=500",
            videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
          },
        ],
      },
    ],
  },
  {
    id: 2,
    title: "Breaking Bad",
    originalTitle: "Breaking Bad",
    description:
      "Un professeur de chimie atteint d'un cancer du poumon inopérable se tourne vers la fabrication et la vente de méthamphétamine pour assurer l'avenir financier de sa famille.",
    releaseDate: "2008-01-20",
    duration: "45-50min par épisode",
    rating: 9.5,
    genres: ["Crime", "Drame", "Thriller"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/HhesaQXLuRY",
    featured: false,
    views: 945670,
    cast: [
      { name: "Bryan Cranston", character: "Walter White", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Aaron Paul", character: "Jesse Pinkman", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Anna Gunn", character: "Skyler White", photo: "/placeholder.svg?height=200&width=200" },
    ],
    creator: "Vince Gilligan",
    language: "Anglais",
    subtitles: ["Français", "Anglais", "Espagnol", "Allemand"],
    vipOnly: false,
    seasons: [
      {
        number: 1,
        title: "Saison 1",
        releaseDate: "2008-01-20",
        episodes: [
          {
            number: 1,
            title: "Pilot",
            description:
              "Un professeur de chimie au lycée apprend qu'il a un cancer du poumon inopérable et décide de se lancer dans la fabrication de méthamphétamine pour subvenir aux besoins de sa famille.",
            duration: "58min",
            thumbnail: "/placeholder.svg?height=300&width=500",
            videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
          },
        ],
      },
    ],
  },
  {
    id: 3,
    title: "Game of Thrones",
    originalTitle: "Game of Thrones",
    description: "Neuf familles nobles rivalisent pour le contrôle du Trône de Fer dans les sept royaumes de Westeros.",
    releaseDate: "2011-04-17",
    duration: "50-60min par épisode",
    rating: 9.2,
    genres: ["Action", "Aventure", "Drame"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/KPLWWIOCOOQ",
    featured: false,
    views: 1245890,
    cast: [
      { name: "Emilia Clarke", character: "Daenerys Targaryen", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Kit Harington", character: "Jon Snow", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Peter Dinklage", character: "Tyrion Lannister", photo: "/placeholder.svg?height=200&width=200" },
    ],
    creator: "David Benioff, D.B. Weiss",
    language: "Anglais",
    subtitles: ["Français", "Anglais", "Espagnol"],
    vipOnly: false,
    seasons: [
      {
        number: 1,
        title: "Saison 1",
        releaseDate: "2011-04-17",
        episodes: [
          {
            number: 1,
            title: "Winter Is Coming",
            description:
              "Le roi Robert Baratheon et sa cour se rendent à Winterfell pour proposer à Ned Stark de devenir la Main du Roi.",
            duration: "62min",
            thumbnail: "/placeholder.svg?height=300&width=500",
            videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
          },
        ],
      },
    ],
  },
  {
    id: 4,
    title: "The Mandalorian",
    originalTitle: "The Mandalorian",
    description:
      "Après la chute de l'Empire, un chasseur de primes solitaire voyage aux confins de la galaxie, loin de l'autorité de la Nouvelle République.",
    releaseDate: "2019-11-12",
    duration: "30-40min par épisode",
    rating: 8.8,
    genres: ["Action", "Aventure", "Science-Fiction"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/aOC8E8z_ifw",
    featured: true,
    views: 765430,
    cast: [
      { name: "Pedro Pascal", character: "The Mandalorian", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Carl Weathers", character: "Greef Karga", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Gina Carano", character: "Cara Dune", photo: "/placeholder.svg?height=200&width=200" },
    ],
    creator: "Jon Favreau",
    language: "Anglais",
    subtitles: ["Français", "Anglais"],
    vipOnly: false,
    seasons: [
      {
        number: 1,
        title: "Saison 1",
        releaseDate: "2019-11-12",
        episodes: [
          {
            number: 1,
            title: "Chapter 1: The Mandalorian",
            description:
              "Un Mandalorien solitaire travaille aux confins de la galaxie, loin de l'autorité de la Nouvelle République.",
            duration: "39min",
            thumbnail: "/placeholder.svg?height=300&width=500",
            videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
          },
        ],
      },
    ],
  },
  // Séries VIP exclusives
  {
    id: 5,
    title: "Exclusivité VIP: Chroniques du Futur",
    originalTitle: "VIP Exclusive: Chronicles of the Future",
    description:
      "Une série d'anticipation qui explore les possibilités technologiques et sociales de notre futur proche.",
    releaseDate: "2023-09-01",
    duration: "55min par épisode",
    rating: 9.3,
    genres: ["Science-Fiction", "Drame", "Anticipation"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/example3",
    featured: true,
    views: 125430,
    cast: [
      { name: "Acteur International", character: "Dr. Futura", photo: "/placeholder.svg?height=200&width=200" },
      { name: "Actrice Primée", character: "Commander Nova", photo: "/placeholder.svg?height=200&width=200" },
    ],
    creator: "Visionnaire Créatif",
    language: "Français",
    subtitles: ["Français", "Anglais", "Espagnol", "Allemand", "Japonais"],
    vipOnly: true,
    seasons: [
      {
        number: 1,
        title: "Saison 1",
        releaseDate: "2023-09-01",
        episodes: [
          {
            number: 1,
            title: "Nouveau Départ",
            description: "L'humanité fait face à un tournant décisif après une découverte scientifique majeure.",
            duration: "58min",
            thumbnail: "/placeholder.svg?height=300&width=500",
            videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
          },
          {
            number: 2,
            title: "Révélations",
            description: "Les conséquences de la découverte commencent à se faire sentir à travers le monde.",
            duration: "54min",
            thumbnail: "/placeholder.svg?height=300&width=500",
            videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
          },
        ],
      },
    ],
  },
  {
    id: 6,
    title: "Exclusivité VIP: Mystères Anciens",
    originalTitle: "VIP Exclusive: Ancient Mysteries",
    description: "Une exploration des civilisations perdues et des mystères non résolus de notre histoire.",
    releaseDate: "2023-08-15",
    duration: "60min par épisode",
    rating: 9.1,
    genres: ["Documentaire", "Histoire", "Mystère"],
    status: "published",
    poster: "/placeholder.svg?height=600&width=400",
    backdrop: "/placeholder.svg?height=1080&width=1920",
    trailer: "https://www.youtube.com/embed/example4",
    featured: true,
    views: 98760,
    cast: [{ name: "Archéologue Renommé", character: "Présentateur", photo: "/placeholder.svg?height=200&width=200" }],
    creator: "Studio Documentaire Premium",
    language: "Français",
    subtitles: ["Français", "Anglais", "Espagnol", "Italien", "Arabe"],
    vipOnly: true,
    seasons: [
      {
        number: 1,
        title: "Saison 1",
        releaseDate: "2023-08-15",
        episodes: [
          {
            number: 1,
            title: "Les Secrets des Pyramides",
            description: "Nouvelles découvertes et théories sur la construction des pyramides égyptiennes.",
            duration: "62min",
            thumbnail: "/placeholder.svg?height=300&width=500",
            videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
          },
          {
            number: 2,
            title: "Atlantide: Mythe ou Réalité",
            description: "Exploration des preuves historiques et archéologiques de l'existence de l'Atlantide.",
            duration: "65min",
            thumbnail: "/placeholder.svg?height=300&width=500",
            videoFile: "https://sample-videos.com/video123/mp4/720/big_buck_bunny_720p_1mb.mp4",
          },
        ],
      },
    ],
  },
]

// Mock data for subscription plans
export const mockSubscriptionPlans = [
  {
    id: "basic",
    name: "Abonnement Standard",
    price: 9.99,
    billingCycle: "monthly",
    features: [
      "Accès à tout le catalogue standard",
      "Streaming HD",
      "Visionnage sur 2 appareils simultanément",
      "Téléchargements limités",
    ],
    isPopular: false,
  },
  {
    id: "premium",
    name: "Abonnement VIP",
    price: 14.99,
    billingCycle: "monthly",
    features: [
      "Accès au catalogue complet (incluant le contenu exclusif)",
      "Streaming 4K HDR",
      "Visionnage sur 4 appareils simultanément",
      "Téléchargements illimités",
      "Avant-premières exclusives",
      "Sans publicité",
      "Support prioritaire",
    ],
    isPopular: true,
  },
  {
    id: "family",
    name: "Abonnement Famille VIP",
    price: 19.99,
    billingCycle: "monthly",
    features: [
      "Tous les avantages de l'abonnement VIP",
      "Visionnage sur 6 appareils simultanément",
      "Contrôle parental avancé",
      "Profils multiples (jusqu'à 6)",
    ],
    isPopular: false,
  },
  {
    id: "premium-annual",
    name: "Abonnement VIP Annuel",
    price: 149.99,
    billingCycle: "annual",
    features: [
      "Tous les avantages de l'abonnement VIP",
      "Économisez 30€ par rapport à l'abonnement mensuel",
      "Accès anticipé aux nouvelles fonctionnalités",
    ],
    isPopular: false,
  },
]

// Mock data for user subscription
export const mockUserSubscription = {
  userId: 1,
  plan: "premium",
  status: "active",
  startDate: "2023-10-15",
  nextBillingDate: "2023-11-15",
  paymentMethod: {
    type: "card",
    last4: "4242",
    expiryMonth: 12,
    expiryYear: 2025,
  },
  billingHistory: [
    {
      id: "inv_123456",
      date: "2023-10-15",
      amount: 14.99,
      description: "Abonnement VIP - Mensuel",
      status: "paid",
      invoiceUrl: "#",
    },
    {
      id: "inv_123455",
      date: "2023-09-15",
      amount: 14.99,
      description: "Abonnement VIP - Mensuel",
      status: "paid",
      invoiceUrl: "#",
    },
    {
      id: "inv_123454",
      date: "2023-08-15",
      amount: 14.99,
      description: "Abonnement VIP - Mensuel",
      status: "paid",
      invoiceUrl: "#",
    },
  ],
}

// Mock data for payment methods
export const mockPaymentMethods = [
  {
    id: "pm_123456",
    type: "card",
    brand: "visa",
    last4: "4242",
    expiryMonth: 12,
    expiryYear: 2025,
    isDefault: true,
  },
  {
    id: "pm_123457",
    type: "card",
    brand: "mastercard",
    last4: "5555",
    expiryMonth: 10,
    expiryYear: 2024,
    isDefault: false,
  },
]
